// CLI constants
export const translations = {
    CLI_TITLE       : '🔐 Crypto CLI',
    CLI_DESCRIPTION : 'Crypto CLI is a simple, yet powerful, command line interface that can be used to perform common cryptographic operations from the command prompt or terminal.',
    CLI_FN_1_TTL    : 'Generate',
    CLI_FN_1_DES    : 'Generates a new OpenPGP key pair. Supports RSA and ECC keys.',
    CLI_FN_2_TTL    : 'Encrypt',
    CLI_FN_2_DES    : 'Encrypts a message.',
    CLI_FN_3_TTL    : 'Decrypt',
    CLI_FN_3_DES    : 'Decrypts a message.',
    CLI_FN_4_TTL    : 'Reformat',
    CLI_FN_4_DES    : 'Reformats signature packets for a key.',
    CLI_FN_5_TTL    : 'Revoke',
    CLI_FN_5_DES    : 'Revokes a key.',
    CLI_FN_6_TTL    : 'Session',
    CLI_FN_6_DES    : 'Generate a new session key object.',
    CLI_FN_7_TTL    : 'Sign',
    CLI_FN_7_DES    : 'Signs a message.',
    CLI_FN_8_TTL    : 'Verify',
    CLI_FN_8_DES    : 'Verifies signatures of cleartext signed message.',
    CLI_FN_9_TTL    : 'Help',
    CLI_FN_9_DES    : 'Get help on a command.',
    CLI_HDL_1_DES   : 'We need you to provide us with the following information:',
    PROMPT_SELECT_TTL  : 'Selection',
    PROMPT_SELECT_DES  : 'Select a function to execute.',
    CLI_ERR_1          : '🔔 You must select a command.',
} as const;
