version = 1

exclude_patterns = [
  "**/dist/**",
  "**/node_modules/**",
  "**/__tests__/**",
  "**/examples/**",
  "packages/crypto-api/src/docs/**",
  "packages/crypto-lib/src/key/**",
  "packages/crypto-lib/src/data/**",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["eslint"]
  environment = ["nodejs"]
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
