// SPDX-License-Identifier: Apache-2.0 OR MIT

import { LocalKmsProvider } from "@sebastienrousseau/crypto-kms";
import { ToolArgs, ToolHandler, jsonResult, parseKey256 } from "./result";

/**
 * In-process KMS backing the "local" provider. Its key-encryption keys
 * are random bytes generated by {@link LocalKmsProvider} and never leave
 * this process, so a wrapped DEK cannot be opened by anyone who merely
 * knows the key label. Keys do not survive a restart.
 */
const localKms = new LocalKmsProvider();

/** Caller-supplied key label -> key id inside {@link localKms}. */
const localKeyIds = new Map<string, string>();

interface KmsRequest {
  provider: string;
  keyId: string;
}

function kmsRequest(args: ToolArgs): KmsRequest {
  const provider = String(args.provider);
  if (provider !== "local") {
    throw new Error(
      `KMS provider '${provider}' is not configured in this server; only 'local' is available`,
    );
  }
  return { provider, keyId: String(args.keyId) };
}

/** Binds each wrapped DEK to the label it was wrapped under. */
function wrapContext(keyId: string): Record<string, string> {
  return { purpose: "crypto-mcp-dek-wrap", keyId };
}

async function localKeyFor(label: string): Promise<string> {
  const existing = localKeyIds.get(label);
  if (existing) return existing;
  const created = await localKms.createKey("aes-256-gcm", "wrap", {
    label,
  });
  localKeyIds.set(label, created.keyId);
  return created.keyId;
}

/** `crypto_kms_wrap`: wrap a 256-bit DEK under a provider-held KEK. */
export const kmsWrap: ToolHandler = async (args) => {
  const { provider, keyId } = kmsRequest(args);
  const dek = parseKey256(args.dek, "dek");
  const kmsKeyId = await localKeyFor(keyId);
  const { ciphertext } = await localKms.encrypt(
    kmsKeyId,
    dek,
    wrapContext(keyId),
  );
  return jsonResult({
    provider,
    keyId,
    status: "wrapped",
    wrappedKey: Buffer.from(ciphertext, "base64").toString("hex"),
  });
};

/** `crypto_kms_unwrap`: recover a DEK wrapped by `crypto_kms_wrap`. */
export const kmsUnwrap: ToolHandler = async (args) => {
  const { provider, keyId } = kmsRequest(args);
  const kmsKeyId = localKeyIds.get(keyId);
  if (!kmsKeyId) {
    throw new Error(`Unknown key '${keyId}' for provider '${provider}'`);
  }
  const wrapped = Buffer.from(String(args.wrappedKey), "hex");
  const { plaintext } = await localKms.decrypt(
    kmsKeyId,
    wrapped.toString("base64"),
    wrapContext(keyId),
  );
  return jsonResult({
    provider,
    keyId,
    status: "unwrapped",
    dek: Buffer.from(plaintext).toString("hex"),
  });
};
