/**
 * Copyright © 2022-2023 The Crypto Service Suite. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */

import * as path from "path";
import * as openpgp from "openpgp";
import { writeKeyOutputs } from "./key-output";
import * as types from "../types/types";

/**
 * Validate and normalise the numeric inputs of {@link generate}, and reject
 * key types that could escape the output directory (CWE-23).
 */
function validateGenerateInput(data: types.dataGenerate): {
  rsaBits: number;
  keyExpirationTime: number;
} {
  const rsaBits = Number(data.rsaBits);
  if (!Number.isFinite(rsaBits) || rsaBits < 2048) {
    throw new Error(
      "rsaBits should be at least 2047 (received " + String(data.rsaBits) + ")",
    );
  }

  const keyExpirationTime = Number(data.keyExpirationTime);
  if (!Number.isFinite(keyExpirationTime) || keyExpirationTime < 0) {
    throw new Error(
      "keyExpirationTime must be a non-negative number of seconds",
    );
  }

  // Sanitize key type early to prevent path traversal (CWE-23).
  if (data.type) {
    const safeType = path.basename(data.type);
    if (safeType !== data.type || safeType.includes("..")) {
      throw new Error("Invalid key type: must not contain path separators");
    }
  }

  return { rsaBits, keyExpirationTime };
}

/**
 * ### generate
 *
 * Generates a new OpenPGP public and private key pair. Supports RSA and ECC
 * keys. The generated primary key has signing capabilities and an
 * encryption subkey is also generated by default.
 *
 * @public
 * @param {Object} data             - Generation parameters.
 * @param {String} data.name        - User name.
 * @param {String} data.email       - User email.
 * @param {String} data.passphrase  - Passphrase used to encrypt the
 *                                    generated private key.
 * @param {String} data.type        - Key type (`rsa` or `ecc`).
 * @param {String} data.curve       - ECC curve name.
 * @param {Number} data.rsaBits     - RSA modulus size in bits. Must be
 *                                    >= 2048.
 * @param {Number} data.keyExpirationTime - Seconds until expiration. Zero
 *                                          disables expiration. Must be
 *                                          >= 0.
 * @param {String} data.format      - Output format.
 * @returns {Promise<object>}       - Armored public/private key and
 *                                    revocation certificate.
 */
export async function generate(data: types.dataGenerate): Promise<object> {
  const { rsaBits, keyExpirationTime } = validateGenerateInput(data);

  const options = {
    date: new Date(),
    userIDs: [{ name: data.name, email: data.email }],
    type: data.type,
    passphrase: data.passphrase,
    rsaBits,
    curve: data.curve,
    keyExpirationTime,
    format: data.format,
  } as Parameters<typeof openpgp.generateKey>[0];

  const { privateKey, publicKey, revocationCertificate } =
    await openpgp.generateKey(options);

  if (!data.type) {
    throw new Error("No key type specified");
  }

  const publicKeyString =
    typeof publicKey === "string" ? publicKey : publicKey.armor();
  const privateKeyString =
    typeof privateKey === "string" ? privateKey : privateKey.armor();

  const base = path.basename(data.type);
  await writeKeyOutputs([
    { name: `${base}.pub`, content: publicKeyString, secret: false },
    { name: `${base}.key`, content: privateKeyString, secret: true },
    { name: `${base}.cert`, content: revocationCertificate, secret: false },
  ]);

  return { publicKey, privateKey, revocationCertificate };
}

/** Default export of the generate function. */
export default generate;
