/**
 * Copyright © 2022-2026 The Crypto Service Suite. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 */

import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import path from "node:path";
import type { FastifyInstance } from "fastify";
import { SUPPORTED_ALGORITHMS } from "@sebastienrousseau/crypto-lib/modern";
import type { CbomPayload } from "../../enterprise/types";

/**
 * Directory holding the `@sebastienrousseau/*` package folders: `packages/`
 * in the monorepo, `node_modules/@sebastienrousseau/` when installed. The
 * same relative path works from `src/routes/v2` and `dist/routes/v2`.
 */
const PACKAGES_ROOT = path.resolve(__dirname, "..", "..", "..", "..");

/**
 * Reads the `version` field of a sibling package's package.json.
 *
 * @param dir - Package folder name, e.g. `"crypto-lib"`.
 * @returns The version, or `"unknown"` when the package is not present.
 */
export function readPackageVersion(dir: string): string {
  try {
    const file = path.join(PACKAGES_ROOT, dir, "package.json");
    return (JSON.parse(readFileSync(file, "utf8")) as { version: string })
      .version;
  } catch {
    return "unknown";
  }
}

/** One entry of the self-reported package inventory. */
export interface InventoryRecord {
  readonly package: string;
  readonly version: string;
  readonly status: "implemented" | "partial" | "placeholder";
  /** Factual statement of what the package implements (field name kept for API compatibility). */
  readonly fipsCompliance: string;
}

/** Self-reported cryptographic inventory; not a compliance verdict. */
export interface DoraSelfAssessment {
  readonly standard: "DORA (EU 2022/2554)";
  readonly article: "Article 9 & Article 13";
  readonly status: string;
  readonly disclaimer: string;
  readonly quantumResistanceRatio: number;
  readonly activePrimitivesCount: number;
  readonly postQuantumPrimitivesCount: number;
  readonly algorithmDeprecationSchedule: ReadonlyArray<{
    readonly algorithm: string;
    readonly category: "symmetric" | "asymmetric";
    readonly sunsetDate: string;
    readonly recommendedMigration: string;
  }>;
  readonly cryptographicInventory: ReadonlyArray<InventoryRecord>;
  readonly timestamp: string;
}

const DISCLAIMER =
  "Self-reported inventory generated by crypto-server. It is not a DORA " +
  "compliance assessment, audit or certification. Counts are algorithm " +
  "identifiers listed by crypto-lib's SUPPORTED_ALGORITHMS, not a measure " +
  "of any deployment. Sunset dates are project recommendations, not " +
  "regulatory deadlines. No module in this suite is FIPS 140-3 validated.";

const POST_QUANTUM_ID = /ml-kem|ml-dsa|slh-dsa|fn-dsa/;

const ALGORITHM_IDS: ReadonlySet<string> = new Set<string>(
  Object.values(SUPPORTED_ALGORITHMS).flat(),
);

const POST_QUANTUM_COUNT = [...ALGORITHM_IDS].filter((id) =>
  POST_QUANTUM_ID.test(id),
).length;

const DEPRECATION_SCHEDULE: DoraSelfAssessment["algorithmDeprecationSchedule"] =
  [
    {
      algorithm: "RSA-2048",
      category: "asymmetric",
      sunsetDate: "2026-12-31T23:59:59Z",
      recommendedMigration: "FIPS 203 ML-KEM-768 / FIPS 204 ML-DSA-65",
    },
    {
      algorithm: "ECDSA (secp256r1 / P-256)",
      category: "asymmetric",
      sunsetDate: "2027-12-31T23:59:59Z",
      recommendedMigration: "FIPS 204 ML-DSA-44 / Ed25519-ML-DSA Hybrid",
    },
    {
      algorithm: "Classical X25519 ECDH",
      category: "asymmetric",
      sunsetDate: "2030-01-01T00:00:00Z",
      recommendedMigration:
        "Hybrid X25519 + ML-KEM-768 (X25519MLKEM768 per RFC 10024 for TLS 1.3)",
    },
    {
      algorithm: "Triple-DES (3DES) & RC4",
      category: "symmetric",
      sunsetDate: "Immediate (Deprecated)",
      recommendedMigration: "AES-256-GCM / ChaCha20-Poly1305",
    },
  ];

const INVENTORY: ReadonlyArray<Omit<InventoryRecord, "version">> = [
  {
    package: "@sebastienrousseau/crypto-lib",
    status: "implemented",
    fipsCompliance:
      "Implements FIPS 203/204/205 algorithms (ML-KEM, ML-DSA, SLH-DSA) and Falcon (FN-DSA) via @noble/post-quantum; not a validated cryptographic module",
  },
  {
    package: "@sebastienrousseau/crypto-wasm",
    status: "placeholder",
    fipsCompliance:
      "Contains no WebAssembly code; all operations run in JavaScript",
  },
  {
    package: "@sebastienrousseau/crypto-kms",
    status: "partial",
    fipsCompliance:
      "AWS KMS and in-memory local providers; GCP, Azure and Vault providers are stubs; PKCS#11 provider is a software simulation; not FIPS 140 validated",
  },
  {
    package: "@sebastienrousseau/crypto-edge",
    status: "implemented",
    fipsCompliance:
      "Web Crypto API adapter with TextEncoder/TextDecoder and base64 fallbacks; not a validated cryptographic module",
  },
  {
    package: "@sebastienrousseau/crypto-cbom",
    status: "implemented",
    fipsCompliance: "Generates CycloneDX 1.6 and SPDX 3.0 CBOM documents",
  },
  {
    package: "@sebastienrousseau/crypto-mcp",
    status: "implemented",
    fipsCompliance: "Model Context Protocol server exposing crypto operations",
  },
  {
    package: "@sebastienrousseau/crypto-lsp",
    status: "implemented",
    fipsCompliance:
      "Language server flagging quantum-vulnerable algorithm names with pattern rules",
  },
];

/** Builds the DORA self-assessment for the current request. */
export function buildDoraSelfAssessment(
  now: Date = new Date(),
): DoraSelfAssessment {
  return {
    standard: "DORA (EU 2022/2554)",
    article: "Article 9 & Article 13",
    status: "Self-assessment (not a compliance verdict)",
    disclaimer: DISCLAIMER,
    quantumResistanceRatio:
      Math.round((POST_QUANTUM_COUNT / ALGORITHM_IDS.size) * 100) / 100,
    activePrimitivesCount: ALGORITHM_IDS.size,
    postQuantumPrimitivesCount: POST_QUANTUM_COUNT,
    algorithmDeprecationSchedule: DEPRECATION_SCHEDULE,
    cryptographicInventory: INVENTORY.map((record) => ({
      ...record,
      version: readPackageVersion(
        record.package.replace("@sebastienrousseau/", ""),
      ),
    })),
    timestamp: now.toISOString(),
  };
}

const CBOM_COMPONENTS: CbomPayload["components"] = [
  {
    type: "cryptographic-asset",
    name: "ML-KEM-768",
    version: "FIPS-203",
    properties: [
      { name: "algorithm-family", value: "Module-Lattice KEM" },
      { name: "quantum-security-category", value: "3" },
      { name: "implementation", value: "@noble/post-quantum" },
    ],
  },
  {
    type: "cryptographic-asset",
    name: "ML-DSA-65",
    version: "FIPS-204",
    properties: [
      { name: "algorithm-family", value: "Module-Lattice Signatures" },
      { name: "quantum-security-category", value: "3" },
      { name: "implementation", value: "@noble/post-quantum" },
    ],
  },
  {
    type: "cryptographic-asset",
    name: "SLH-DSA-128s",
    version: "FIPS-205",
    properties: [
      { name: "algorithm-family", value: "Stateless Hash-Based Signatures" },
      { name: "quantum-security-category", value: "1" },
      { name: "implementation", value: "@noble/post-quantum" },
    ],
  },
  {
    type: "cryptographic-asset",
    name: "Composite-Hybrid-X25519-ML-KEM-768",
    version: "RFC-10024",
    properties: [
      { name: "algorithm-family", value: "Dual Encapsulation Hybrid KEM" },
      { name: "defense-in-depth", value: "classical-plus-post-quantum" },
      { name: "implementation", value: "@noble/curves + @noble/post-quantum" },
    ],
  },
];

/** Builds a CycloneDX CBOM with a fresh serial number for each request. */
export function buildCbom(now: Date = new Date()): CbomPayload {
  const serverVersion = readPackageVersion("crypto-server");
  return {
    bomFormat: "CycloneDX",
    specVersion: "1.6",
    serialNumber: `urn:uuid:${randomUUID()}`,
    version: 1,
    metadata: {
      timestamp: now.toISOString(),
      tools: [
        {
          vendor: "Sebastien Rousseau",
          name: "@sebastienrousseau/crypto-server",
          version: serverVersion,
        },
      ],
      component: {
        type: "framework",
        name: "@sebastienrousseau/crypto-server",
        version: serverVersion,
        description:
          "Fastify REST API exposing crypto-lib operations, including post-quantum algorithms",
      },
    },
    components: CBOM_COMPONENTS,
  };
}

/** Registers the v2 compliance endpoints (DORA self-assessment and CycloneDX CBOM). */
export default (app: FastifyInstance): void => {
  app.get(
    "/v2/compliance/dora",
    {
      schema: {
        tags: ["Compliance"],
        summary: "DORA cryptographic inventory (self-assessment)",
        description:
          "Returns a self-reported cryptographic inventory, post-quantum algorithm counts and recommended sunset dates. It is not a compliance assessment or verdict under Regulation (EU) 2022/2554.",
        response: {
          200: {
            type: "object",
            properties: {
              data: {
                type: "object",
                properties: {
                  standard: { type: "string" },
                  article: { type: "string" },
                  status: { type: "string" },
                  disclaimer: { type: "string" },
                  quantumResistanceRatio: { type: "number" },
                  activePrimitivesCount: { type: "number" },
                  postQuantumPrimitivesCount: { type: "number" },
                  algorithmDeprecationSchedule: { type: "array" },
                  cryptographicInventory: { type: "array" },
                  timestamp: { type: "string" },
                },
              },
            },
          },
        },
      },
    },
    async () => {
      return { data: buildDoraSelfAssessment() };
    },
  );

  app.get(
    "/v2/compliance/cbom",
    {
      schema: {
        tags: ["Compliance"],
        summary:
          "Cryptographic Bill of Materials (CBOM) in CycloneDX 1.6 format",
        description:
          "Emits a machine-readable CycloneDX 1.6 CBOM listing the post-quantum algorithms this service implements. It is informational input for CRA and DORA work and does not by itself establish compliance.",
      },
    },
    async (_request, reply) => {
      reply.header(
        "Content-Type",
        "application/vnd.cyclonedx+json; charset=utf-8",
      );
      return buildCbom();
    },
  );
};
