name: "Crypto Service Suite CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm -r run build

      - name: Test
        run: pnpm -r run test

      - name: Coveralls Crypto-Api
        uses: coverallsapp/github-action@v2
        with:
          base-path: packages/crypto-api
          flag-name: crypto-api
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          file: ./packages/crypto-api/coverage/lcov.info

      - name: Coveralls Crypto-Cli
        uses: coverallsapp/github-action@v2
        with:
          base-path: packages/crypto-cli
          flag-name: crypto-cli
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          file: ./packages/crypto-cli/coverage/lcov.info

      - name: Coveralls Crypto-Lib
        uses: coverallsapp/github-action@v2
        with:
          base-path: packages/crypto-lib
          flag-name: crypto-lib
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          file: ./packages/crypto-lib/coverage/lcov.info

      - name: Coveralls Crypto-Server
        uses: coverallsapp/github-action@v2
        with:
          base-path: packages/crypto-server
          flag-name: crypto-server
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          file: ./packages/crypto-server/coverage/lcov.info

  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
